config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :characters, only: %i[show create] do
    resources :illustrations, only: :create
  end
  resources :illustrations, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
require 'open-uri'

class Character < ApplicationRecord
  after_commit :generate_description, on: :create

  has_many_attached :illustrations
  has_one_attached :photo # This is the source photo of the character

  def attach_illustration_from_url(url)
    illustrations.attach(io: URI.open(url), filename: "heroifyme_#{SecureRandom.hex(8)}.png")
  end

  private

  def generate_description
    character_description = DescribePhoto.new(photo.url).call
    update(description: character_description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def create
    @character = Character.new(character_params)

    if @character.save!
      redirect_to character_path(@character), notice: 'Your character has been created!'
    else
      render 'pages/home'
    end
  end

  def show
    @character = Character.find(params[:id])
    @illustrations = @character.illustrations.order(created_at: :desc).limit(18)
  end

  private

  def character_params
    params.require(:character).permit(:photo)
  end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController

  # POST characters/:character_id/illustrations
  def create
    # Find the character
    character = Character.find(params[:character_id])
    situation = params[:situation]
    # Create an illustration using OpenAI DALL-E
    prompt = GeneratePrompt.new(character.description, situation).call
    image_url = GenerateIllustration.new(prompt).call
    # Attach the generate illustration to the Character instance
    character.attach_illustration_from_url(image_url)

    # Redirect to character show page
    redirect_to character_path(character)
  end

  def destroy
    @illustration = ActiveStorage::Attachment.find(params[:id])
    @character = @illustration.record
    @illustration.purge
    redirect_to character_path(@character), notice: 'The illustration has been deleted!'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @illustrations = Character.with_attached_illustrations.order(created_at: :desc).map(&:illustrations).flatten.shuffle.first(20)
    @character = Character.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def featured?(illustration_id, index)
    if params[:featured].present?
      illustration_id == params[:featured].to_i
    else
      index == 0
    end
  end
end

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/application/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/application/_logo.html.erb
<%= link_to root_path do %>
  <i class="heroify-logo fa-solid fa-bolt-lightning fa-3x"></i>
<% end %>

app/views/characters/_form.html.erb
<%= simple_form_for(character) do |f| %>
  <div class="form-inputs">
    <%= f.input :photo, label: false %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Create your Hero", class: 'btn btn-primary w-100' %>
  </div>
<% end %>

app/views/characters/index.html.erb
<div class="lightbox my-5">
  <div class="row">
    <div class="col-lg-8 offset-2">
      <%= render 'characters/form', character: Character.new %>
      <div class="image-grid">
        <% @characters.each do |character| %>
          <%= link_to character_path(character) do %>
            <% if character.images.attached? %>
              <%= cl_image_tag character.images.last.key, class: "w-100 shadow-1-strong rounded" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<%= render "logo" %>
<div class="container">
  <div class="illustration-form-container position-fixed z-3<%= ' with-illustrations' if @illustrations.present? %><%= ' with-photo' if @character.respond_to?(:photo) && @character.photo.attached? %>">
    <% if @character.respond_to?(:photo) %>
      <%= cl_image_tag @character.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: 'avatar' %>
    <% end %>
    <%= form_tag(character_illustrations_path(@character), method: :post) do %>
      <div class="form-inputs">
        <%= text_field :situation, nil, placeholder: 'What should your hero be doing?', class: 'w-100 p-1' %>
      </div>
      <div class="form-actions">
        <%= submit_tag 'Heroify!', class: 'btn btn-primary w-100' %>
      </div>
    <% end %>
  </div>
  <div class="vw-100 vh-100 position-fixed top-0 start-0 z-n1">
    <% if @illustrations.present? %>
      <div class="character-grid">
        <% @illustrations.each_with_index do |illustration, idx| %>
          <div class="position-relative grid-item <%= 'featured' if featured?(illustration.id, idx) %>">
            <%= link_to character_path(illustration.record, featured: illustration.id) do %>
              <%= cl_image_tag illustration.key, class: "w-100 shadow-1-strong rounded" %>
            <% end %>
            <%= link_to cloudinary_url(illustration.key), class: 'position-absolute top-0 end-0 m-2', target: :blank do %>
              <i class="fa-solid fa-download"></i>
            <% end %>
            <%= link_to illustration_path(illustration.id), method: :delete,
                        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                        class: 'position-absolute bottom-0 end-0 m-2' do %>
              <i class="fa-solid fa-skull-crossbones"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= image_tag 'no_images.png', style: 'object-fit: cover', class: 'w-100 vh-100 shadow' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeroifyMe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'ios_pwa_links' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="character-form-container position-fixed z-3">
  <div class="text-center text-primary mb-2">
    <h1><i class="fa-solid fa-bolt-lightning"></i> HeroifyMe!</h1>
  </div>
  <%= render 'characters/form', character: @character %>
</div>
<div class="vw-100 vh-100 position-fixed top-0 start-0 z-n1">
  <div class="home-grid">
    <% @illustrations.shuffle.each do |illustration| %>
      <div class="position-relative grid-item">
        <%= cl_image_tag illustration.key, transformation: [{width: 500, crop: "scale"}, {quality: "auto", fetch_format: "auto" }], class: 'w-100' %>
        <%= link_to character_path(illustration.record, featured: illustration.id), class: 'position-absolute top-0 start-0 m-2' do %>
          <i class="fa-solid fa-bolt z-3"></i>
        <% end %>
        <%= link_to cloudinary_url(illustration.key), class: 'position-absolute top-0 end-0 m-2', target: :blank do %>
          <i class="fa-solid fa-download z-3"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>